### ISSUE TITLE
needs more cowbell.

### ISSUE THREAD

**Issue by ryft** [amitoj93/hello-world#3]
dong
dong
dong

**Comment by amitoj93** [comment]
Is this version acceptable? https://github.com/amitoj93/hello-world/blob/v2-with-cowbell/README.md

**Comment by amitoj93** [comment]
Also having your face as my profile pic is confusing the shit out of me

**Comment by ryft** [comment]
ac18967 looks perfect

**Comment by ryft** [comment]
yep, this conversation looks particularly one-sided

**Comment by amitoj93** [comment]
You histrionic
